version: '3.1'

services:

  db:
    image: mysql
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
#      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: lmc_user

  phpmyadmin:
    image: phpmyadmin
    restart: no
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
